### ISSUE TITLE
Repeating parameterised options

### ISSUE THREAD

**Issue by rgrannell1** [felixSchl/docopt.js#16]
Hello,

I'm really glad to see that docopt.coffee has a competitor (written in Purescript!), as docopt.coffee is a little buggy, difficult to debug, and unmaintained.

Will neodoc support repeating parameterised options ([docopt.coffee doesn't properly support them](https://github.com/docopt/docopt.coffee/issues/15))? 

I'm looking forward to porting from docopt to neodoc :+1:

**Comment by felixSchl** [comment]
Hey, see the commit above, I have added tests which all pass in neodoc. Do they match your expectations?

**Comment by rgrannell1** [comment]
Thanks for testing that corner-case; the expected output looks good :)

**Comment by felixSchl** [comment]
Hey, over the last days it became apparent to me that the comma notation (`-f 123,123`) is too specific and won't hold up, I think. What about space separated values or colon separated, or semicolon... Also what if the value you pass happens to have a unintentional comma in it. I consider this a big flaw and will remove it and treat these values as regular strings in coming releases. Maybe we can add a tag to the description sections that triggers this style of parsing? I could imagine it be more flexible to have the providing program perform the expansion in such cases, e.g. bash: `-f{123,123,123}`.
