### ISSUE TITLE
Remove left & right trimming?

### ISSUE THREAD

**Issue by matthewmueller** [felixSchl/docopt.js#71]
Sorry one more thing that would be nice to have. Right now the library trims the left and right spacing from the input. The thing I love about this library is that you can sort of make your CLI however you want with just a few standard expressions. For my CLI, I'm finding that adding a bit of spacing would make things a bit easier to read.

**Comment by felixSchl** [comment]
Agreed. Maybe a python like `textwrap.dedent` would be fair? Would you be able to provide a simple example? And lastly, why would you care about trailing space on the right?

**Comment by matthewmueller** [comment]
i think you could use https://github.com/sindresorhus/strip-indent to do a dedent. here's what I'm working with:

<img width="753" alt="screen shot 2016-08-16 at 10 44 14 am" src="https://cloud.githubusercontent.com/assets/170299/17687364/9b81003a-639e-11e6-8efc-6826f1794828.png">

Much better than the output of commander, but I'd love to give it a bit of padding :-)

**Comment by felixSchl** [comment]
That's one good looking CLI. Makes me wonder what does your neodoc source string look like to get all the colors going? I'd imagine a lot of these guys: `${chalk.blue("usage:")}`. Makes me think if we need to add colouring support into neodoc to highlight section titles and comments. But that's a separate issue. In terms of this, to add the padding, why don't we just strip all leading and trailing empty lines but keep the left indent as-is. I think that would be suitable.

**Comment by felixSchl** [comment]
Do you mind providing a simple example for this? I have checked the sources, I am actually not de-denting the `--help` output, only the shortened usage section help text. The only thing I do is trimming the string: https://github.com/felixSchl/neodoc/blob/1a62a3715cb80df17e8c38c61c89149e9f41fbee/src/Docopt/Docopt.purs#L143.

**Comment by matthewmueller** [comment]
Certainly, here's a trimmed version of the code:

**thimble**

``` js
#!/usr/bin/env node

const { run } = require('neodoc')
const chalk = require('chalk')
const argv = run(`

  ${chalk.inverse(' THIMBLE ')} A scaffolding system that grows with you.

  ${chalk.blue('I. Usage')}:

    thimble <command> [<args>...]
    thimble -h | --help
    thimble --version


`)
```

**run:**

```
./thimble --help
```

You'll notice that despite having some extra padding and whitespace on both sides, it'll still hug the left side. It's totally your call on what you think is best, but I _think_ since most people will have this code top-level (as opposed to inside an if statement block), it won't be unexpected to not dedent.

**Comment by matthewmueller** [comment]
On second thought, I definitely think you should just leave the dedenting, trimming up to the implementer of the CLI. 
- If I don't want left padding: `run(myCLI.trimLeft())`
- If I don't want right padding: `run(myCLI.trimRight())`
- If I don't want any padding: `run(myCLI.trim())`
- If I want dedent, I can use strip-indent and do `run(strip(myCLI))`

This probably allows you to reduce the codebase a bit.

**Comment by felixSchl** [comment]
Thank you for providing the example and I agree with your reasoning. But what do you think about removing the very first (and maybe last) newline character? This way if you want padding, you just add another line. E.g.:

```
run(`
usage: foo bar
`)
```

```
run(`

usage: foo bar

`)
```

I've updated the JS test bed to able to test these things and have made corresponding adjustments to the code, but it would be good if we could agree on this. In part I disagree with myself with the above because the behavior is implicit and cannot be turned off. However, I think it would make it more usable and avoids extra function call clutter or even bringing in another dependency.

Edit: To re-iterate: what I mean is that this approach would be less radical than trimming to the first non-ws character (only remove first and last empty line) and it would not mess with the indentation at all.

**Comment by felixSchl** [comment]
I've implemented the above behavior and adjusted the test case:

https://github.com/felixSchl/neodoc/blob/a1b375ff7cbec633294ab25dbbb8c110a50e79e2/test-js/test.js#L195-L213

It just boils down to this regular expression: https://github.com/felixSchl/neodoc/blob/a1b375ff7cbec633294ab25dbbb8c110a50e79e2/src/Docopt/Docopt.purs#L185

...which reminds me of http://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016 :/ But I think our inputs are small enough and in complete control of the user that this is non-issue.

**Comment by matthewmueller** [comment]
> But what do you think about removing the very first (and maybe last) newline character?

Totally agree! Forgot about the first and last `\n`

Awesome, thanks for your hard work!

**Comment by felixSchl** [comment]
Sweet, I'll merge this then and create a patch release.
