### ISSUE TITLE
Unknown command error for positional sub commands.

### ISSUE THREAD

**Issue by steve-a-jones** [felixSchl/docopt.js#78]
Hey @felixSchl!

I was playing around with the git example and would like to hear your thoughts regarding the "unknown command" output from `neodoc.run` when defining commands abstractly with positional notation.

(Command in literal notation)

```
usage: git add [options] [--] <pathspec>...
```

(Behavior)

```
$ git foo
git: unknown command foo
```

The above works as expected, but we of course prefer to break out the command docs into their own modules as you have done with the `git` example by representing our command positionally..

```
usage: git [--version] [--help]  [<command> [<args>]...]
```

And then do a runtime require with `args['<command>']`.

How can we have `neodoc.run` throw the same "unknown command" in this instance? I was thinking about having an intermediary parser with all of the commands defined explicitly ...

```
usage: git (add|commit|rebase, etc...) [<args>...]
```

.. which would then result in the command not found error. 

Is there a better way? Appreciate your thoughts.

**Comment by felixSchl** [comment]
You have analyzed the issue correctly. I plan on supporting command choices, where in the option section you can associate a set of known commands with a positional which is often the case. For now, as of v1, there are pre- and postsolve transforms that can be used to achieve this. Simply traverse the data structure you get in the callback and replace your "`<command>`" element with a group that contains each of the commands as a branch:

```
type: elem
elem: { name: "<command>" }
```

becomes sth like:

```
type: group
optional: false
repeatable: false
branches: [[ { type: elem, elem: { name: "add" } }, ... ], [ ... ]]
```

There are currently no traversal utilities, but we can add them to the codebase as usage patterns emerge.

**Comment by steve-a-jones** [comment]
Excellent, makes sense, thank you - so I am essentially expanding the command element similarly to the [option] references. I guess it also makes sense to start pre parsing my specs to make this type of stitching a bit easier.

Appreciate the help!
