### ISSUE TITLE
Optional positional arguments

### ISSUE THREAD

**Issue by nickserv** [felixSchl/docopt.js#92]
It seems that all positional arguments using `<>` must be required, while only flags and their values may be optional. It would be handy to support the `[]` syntax that's popular with other CLI libraries like commander and yargs, which represents an optional positional argument.

My current use case is for [cdnm](https://github.com/nickmccurdy/cdnm), which has an optional `path` argument for each command. If `path` is given the commands operate on files, otherwise they operate on stdin and stdout.

__EDIT:__ This is actually supported with the `[<>]` syntax.

**Comment by felixSchl** [comment]
Are you able to share the neodoc text that is not working for you? `usage: foo [path]` should definitely be possible

**Comment by felixSchl** [comment]
I had a quick look over your link (and fixed the link in your issue report). That should be 100% possible.

Something like:

```
usage: cdnm list [<path>]
   or: cdnm outdated [<path>]
   or: cdnm package [<path>]
   or: cdnm update [<path>]
```

Then later:

```js
args = neodoc.run(...)
if (args['list']) {
  if (args['<path>']) {
    ...
  } else {
   ... stdin or stdout here
  }
} else if (args['outdated']) {
} else if ...
```

**Comment by nickserv** [comment]
Here's what I tried:

```
CDN Manager

Usage:
  cdnm list [path]
  cdnm outdated [path]
  cdnm package [path]
  cdnm update [path]
  cdnm -h | --help
  cdnm --version

Options:
  -h --help     Show this screen.
  --version     Show version.
```

It seems like the `[<…>]` syntax works fine but I thought it was `[…]`, thanks! I must have missed `optional groupings` in the readme, or not expected it to work for positional arguments.

Would it be possible to also support the `[…]` syntax for convenience or would that be ambiguous?

**Comment by felixSchl** [comment]
The difference between `[path]` and `[<path>]`, or more generally `path` and `<path>` is that `path` only matches the literal string `"path"`, whereas `<path>` matches anything that does not look like a flag.

**Comment by nickserv** [comment]
I see, so the `[…]` syntax would have to be reserved for optional keywords or other literal string arguments, right? In that case, it seems like I misunderstood this and should have had a closer look at the readme, and this can be closed. Thanks for your explanation!

**Comment by felixSchl** [comment]
Yup, the `[...]` denotes optional groupings. You can also make entire branches optional `usage: program [foo qux]` meaning that if `foo` is matched it must also match `qux` in order to succeed.
