### ISSUE TITLE
Problem when option is substring of other option

### ISSUE THREAD

**Issue by LinusU** [felixSchl/docopt.js#94]
I'm running into a little problem with one option that is an extension of the name of another option. I think this is best explained with an example:

```text
Scandium

usage:
  scandium create [options]

options:
  --env=<key=value>...         Set environmental variables. Example: "--env NODE_ENV=production".
  --env-from-file=<path>       Read and set environmental variables from the specified file.
```

Trying to use as such:

```text
scandium create --env TEST=yes --env-from-file stage.env
```

Results in:

```js
{
  '--env': ['TEST=yes', '-from-file', 'stage.env']
}
```

When I expected it to parse into:

```js
{
  '--env': ['TEST=yes'],
  '--env-from-file': 'stage.env'
}
```

**Comment by LinusU** [comment]
If anyone else runs into this, I'm currently using the following workaround 😂 

```js
const envFromFileIndex = process.argv.indexOf('--env-from-file', 2)

if (envFromFileIndex > 0 && envFromFileIndex < process.argv.length - 1) {
  process.argv.splice(envFromFileIndex, 1)
  process.argv[envFromFileIndex] = '--env-from-file=' + process.argv[envFromFileIndex]
}
```

**Comment by felixSchl** [comment]
Interesting :) Another less invasive workaround would be:

```javascript
const args = neodoc.run(...)
if ((args['--env'] && args['--env'][0] == '-from-file') || args['--env-from-file']) {
  // ...
}
```

This works because if the user explicitly binds like this `--env-from-file=foobar`, then it will always assign to `--env-from-file`.

**Comment by felixSchl** [comment]
Does it seem reasonable to disallow this altogether? `--env-x`, so an argument cannot start with a `-` if it's not explicitly bound (i.e. via `=`). That would be a breaking change, but also make a lot of sense, to me at least.

**Comment by albinekb** [comment]
That won't work with them both at the same time though? 🤔  https://github.com/LinusU/scandium/blob/master/lib/tasks.js#L39-L45

Indeed that would be nice. It could still start with `-` if you have a space, bind it via `=` or wrap it in `""`? 

Is it currently supported to do `--flagvalue` without anything between the flag and value? 😱

**Comment by felixSchl** [comment]
> Is it currently supported to do --flagvalue without anything between the flag and value? :scream:

https://github.com/felixSchl/neodoc/blob/af8ad85858f10acaadf0fece477c3c2254568c7a/src/Neodoc/ArgParser/Argument.purs#L151-L161

So, yes, that's the current behaviour and mirrors that of short options. What do you propose? From my perspective the easiest would be to remove the entire case above.

**Comment by albinekb** [comment]
That's neat. I've never used options like that, not that useful I think and it's also hard to read 🙂 Yes, I think it makes more sense to support more combinations of options rather than short options. @LinusU ?

Let's say you had a flag called `--flag` and then you typoed it to `--flagg test`, that would set `g test` to `--flag`? Better if that throws 👍

**Comment by felixSchl** [comment]
> Let's say you had a flag called --flag and then you typoed it to --flagg test, that would set g test to --flag? Better if that throws 👍

Not entirely, you still need to specify the flag to take an argument. Also it would only consume a single argument, unless you specify that the argument is to be repeated:

```
usage: foo --flag
$ foo --flagd test
# Unknown option --flagd
```

```
usage: foo --flag=<arg>...
$ foo --flagd test
# flag → ["d","test"]
```

```
usage: foo --flag=<arg>
$ foo --flagd test
# Unknown command test
```

But regardless, I agree that this is counter-intuitive. I think removing that case would be a better user experience, but I'll have to do a major version bump. Will make the update shortly.

**Comment by albinekb** [comment]
Found another thing that is a bit wonky related to this.

We added an arg called --name-postfix, we also have --name.
```
 --name-postfix "--prod"
```
Will tell me there's no option called --name-postfix.

Using it with explicit binding works, `--name-postfix=--prod`

**Comment by felixSchl** [comment]
Are you able to share the usage string so I can see what's going on? While I am surprised about the error message you are getting, you won't get around having to use an explicit binding if the value looks like a flag.

**Comment by albinekb** [comment]
Ah, thats true 👍 I'll see 
Here's the usage: https://github.com/LinusU/scandium/blob/master/app.js#L29

My bad, it actually said "option requires argument" 🙈  So that's correct
![image](https://user-images.githubusercontent.com/5027156/36383608-f2c7b180-158c-11e8-8ef0-56e0c78b25a8.png)


Shouldn't `--name-postfix "--stage"` work though? (maybe it does, haven't tested)

**Comment by felixSchl** [comment]
I've updated the code, it would be really helpful if you could lend a pair of eyes over the changes to the testcases, to make sure there's no oversight of anything: https://github.com/felixSchl/neodoc/commit/d6f2a0ef419092702652d3b7b3db6eb2a653ae38. I've also published a prerelease version to npm for you to test out under `neodoc@2.0.0-fix-94`. I won't get around a major bump since it's not only changing the behaviour of library user's, but for users of library users.

**Comment by albinekb** [comment]
Awesome! I added a comment over there for the test cases I couldn't see. I'll try updating to that version and see if it works like expected, thanks!

**Comment by felixSchl** [comment]
Awesome, I've added a few more test cases as well, just to be sure

**Comment by albinekb** [comment]
```
❯ ./app.js create --env a=b d=e --env-from-file ./TEST
args { create: true,
  '--env': [ 'a=b', 'd=e' ],
  '--env-from-file': './TEST' }
```

`neodoc@2.0.0-fix-94` fixes this issue correctly 👌 🙌

**Comment by felixSchl** [comment]
Ok cool, the new behaviour is now available in `neodoc@2.0.0`. Thank you for the report :)

**Comment by albinekb** [comment]
Thanks for fixing it 🙏 Love this lib!

**Comment by LinusU** [comment]
😍 wow

Awesome, to see this resolved so quickly, on vacation now but will take a look in a few days 🙌
