### ISSUE TITLE
Changelog for 2.0.0

### ISSUE THREAD

**Issue by yvele** [felixSchl/docopt.js#95]
`2.0.0` is a major version, could you explain what exactly is break in [CHANGELOG.md](https://github.com/felixSchl/neodoc/blob/development/CHANGELOG.md) and/or in [release notes](https://github.com/felixSchl/neodoc/releases/tag/v2.0.0)?

Exploring the commit is not really easy (is d6f2a0ef419092702652d3b7b3db6eb2a653ae38 or 23cb731638fbf42b1eddcb8d33929c784ad446fd the breaking stuff?)

Thank you!

@jagu-sayan CC

**Comment by felixSchl** [comment]
I haven't released an update in a while and it slipped my mind. I have updated the changelog and release tag description now. Thanks for the reminder :)

**Comment by yvele** [comment]
Thanks! 👍
